import{S as m,i as c}from"./assets/vendor-8c59ed88.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();document.querySelector(".loader");let f=new m(".gallery a");const a=document.querySelector(".img-list");function h(s){const o=s.hits.map(t=>`<li class="list-el">
                <a href="${t.largeImageURL}"><img src='${t.webformatURL}' alt='${t.tags}'></a>
                <div class="content">
                    <div class="item"><h3>Likes</h3><p>${t.likes}</p></div>
                    <div class="item"><h3>Views</h3><p>${t.views}</p></div>
                    <div class="item"><h3>Comments</h3><p>${t.comments}</p></div>
                    <div class="item"><h3>Downloads</h3><p>${t.downloads}</p></div>
                </div>
            </li>`).join("");a.textContent="",a.insertAdjacentHTML("beforeend",o),l(),f.refresh()}function p(s){const o="https://pixabay.com",t="/api/",i=new URLSearchParams({key:"44710558-f9f1e7058b6d6169ae4ab4229",image_type:"photo",orientation:"horizontal",safesearch:!0,q:`${s}`}),e=`${o}${t}?${i}`;return fetch(e).then(r=>{if(r.ok)return r.json();throw new Error(r.status)})}const d=document.querySelector(".form-el"),y=document.querySelector(".img-list"),u=document.querySelector(".loader");function g(){u.classList.remove("visually-hidden")}function l(){u.classList.add("visually-hidden")}d.addEventListener("submit",s=>{s.preventDefault();const o=d.elements[0].value.trim();if(g(),o)p(o).then(t=>{if(t.hits.length===0)throw l(),y.innerHTML="",new Error("Error! Nothing to load");h(t)}).catch(t=>{c.show({title:"Sorry",message:"there are no images matching your search query. Please try again!",color:"red"})});else{l(),c.error({message:"Info Search input must be filled!"});return}});
//# sourceMappingURL=commonHelpers.js.map
